version: '3'

#镜像说明:
#单机版：noearorg/luffy-jtl ，使用h2嵌入式数据库
#集群版：noearorg/luffy-jtc ，使用mysql8数据库

services:
  teamx:
    image: noearorg/luffy-jtl 
    container_name: teamx
    environment:
      - luffy.add=teamx.noear     #添加luffy插件，多个以,隔开
      - luffy.init=/teamx/__init  #启动后的初始化脚本
      - luffy.model=2             #运行模式（2:多人模式）
    ports:
      - "8080:8080"
    volumes:
      - "./luffy_ext:/luffy_ext"


